
import React from 'react';
import { 
  CreditCard, 
  Smartphone, 
  Wifi, 
  Zap, 
  Music, 
  Tv, 
  ShieldCheck, 
  Globe,
  Settings,
  Plus,
  Trash2,
  CheckCircle2,
  DollarSign,
  Briefcase,
  HeartPulse,
  Monitor,
  Plane,
  TrendingUp,
  FileText,
  Lock,
  MessageSquare,
  Coffee,
  Utensils,
  ShoppingBag,
  Gamepad2,
  Home
} from 'lucide-react';

export const CATEGORIES = [
  { id: 'saas', name: 'Software/SaaS', icon: <Globe className="w-4 h-4" /> },
  { id: 'food', name: 'Food & Drink', icon: <Utensils className="w-4 h-4" /> },
  { id: 'entertainment', name: 'Entertainment', icon: <Gamepad2 className="w-4 h-4" /> },
  { id: 'shopping', name: 'Shopping', icon: <ShoppingBag className="w-4 h-4" /> },
  { id: 'housing', name: 'Housing/Rent', icon: <Home className="w-4 h-4" /> },
  { id: 'taxes', name: 'Taxes/Gov', icon: <FileText className="w-4 h-4" /> },
  { id: 'hardware', name: 'Hardware/Gear', icon: <Monitor className="w-4 h-4" /> },
  { id: 'insurance', name: 'Insurance/Health', icon: <HeartPulse className="w-4 h-4" /> },
  { id: 'marketing', name: 'Marketing/Ads', icon: <TrendingUp className="w-4 h-4" /> },
  { id: 'travel', name: 'Travel/Transport', icon: <Plane className="w-4 h-4" /> },
  { id: 'office', name: 'Workspace/Rent', icon: <Briefcase className="w-4 h-4" /> },
  { id: 'utility', name: 'Utilities/Comm', icon: <Zap className="w-4 h-4" /> },
  { id: 'other', name: 'Other', icon: <CreditCard className="w-4 h-4" /> },
];

export const POPULAR_BRANDS = [
  { name: 'Netflix', domain: 'netflix.com' },
  { name: 'Spotify', domain: 'spotify.com' },
  { name: 'Adobe', domain: 'adobe.com' },
  { name: 'Figma', domain: 'figma.com' },
  { name: 'Google', domain: 'google.com' },
  { name: 'Amazon', domain: 'amazon.com' },
  { name: 'Claude', domain: 'anthropic.com' },
  { name: 'ChatGPT', domain: 'openai.com' },
  { name: 'Slack', domain: 'slack.com' },
  { name: 'Zoom', domain: 'zoom.us' },
  { name: 'Vercel', domain: 'vercel.com' },
  { name: 'Notion', domain: 'notion.so' },
  { name: 'Canva', domain: 'canva.com' },
  { name: 'Mailchimp', domain: 'mailchimp.com' },
  { name: 'Loom', domain: 'loom.com' },
  { name: '1Password', domain: '1password.com' },
];

export const CURRENCY_LIST = [
  { code: 'USD', name: 'US Dollar' },
  { code: 'EUR', name: 'Euro' },
  { code: 'GBP', name: 'British Pound' },
  { code: 'JPY', name: 'Japanese Yen' },
  { code: 'CAD', name: 'Canadian Dollar' },
  { code: 'AUD', name: 'Australian Dollar' },
  { code: 'CHF', name: 'Swiss Franc' },
  { code: 'CNY', name: 'Chinese Yuan' },
  { code: 'HKD', name: 'Hong Kong Dollar' },
  { code: 'NZD', name: 'New Zealand Dollar' },
  { code: 'SEK', name: 'Swedish Krona' },
  { code: 'KRW', name: 'South Korean Won' },
  { code: 'SGD', name: 'Singapore Dollar' },
  { code: 'NOK', name: 'Norwegian Krone' },
  { code: 'MXN', name: 'Mexican Peso' },
  { code: 'INR', name: 'Indian Rupee' },
  { code: 'RUB', name: 'Russian Ruble' },
  { code: 'ZAR', name: 'South African Rand' },
  { code: 'TRY', name: 'Turkish Lira' },
  { code: 'BRL', name: 'Brazilian Real' },
  { code: 'TWD', name: 'Taiwan Dollar' },
  { code: 'DKK', name: 'Danish Krone' },
  { code: 'PLN', name: 'Polish Zloty' },
  { code: 'THB', name: 'Thai Baht' },
  { code: 'IDR', name: 'Indonesian Rupiah' },
  { code: 'HUF', name: 'Hungarian Forint' },
  { code: 'CZK', name: 'Czech Koruna' },
  { code: 'ILS', name: 'Israeli Shekel' },
  { code: 'CLP', name: 'Chilean Peso' },
  { code: 'PHP', name: 'Philippine Peso' },
  { code: 'AED', name: 'UAE Dirham' },
  { code: 'COP', name: 'Colombian Peso' },
  { code: 'SAR', name: 'Saudi Riyal' },
  { code: 'MYR', name: 'Malaysian Ringgit' },
  { code: 'RON', name: 'Romanian Leu' },
  { code: 'ARS', name: 'Argentine Peso' },
  { code: 'PEN', name: 'Peruvian Sol' },
  { code: 'VND', name: 'Vietnamese Dong' },
  { code: 'UAH', name: 'Ukrainian Hryvnia' },
  { code: 'NAD', name: 'Namibian Dollar' },
  { code: 'NGN', name: 'Nigerian Naira' },
  { code: 'EGP', name: 'Egyptian Pound' },
  { code: 'KES', name: 'Kenyan Shilling' },
  { code: 'GHS', name: 'Ghanaian Cedi' },
  { code: 'PKR', name: 'Pakistani Rupee' },
  { code: 'BDT', name: 'Bangladeshi Taka' },
  { code: 'MAD', name: 'Moroccan Dirham' },
  { code: 'DOP', name: 'Dominican Peso' },
  { code: 'CRC', name: 'Costa Rican Colón' },
  { code: 'UYU', name: 'Uruguayan Peso' },
  { code: 'PYG', name: 'Paraguayan Guarani' },
  { code: 'BOB', name: 'Bolivian Boliviano' },
].sort((a, b) => a.code.localeCompare(b.code));

export const ICONS = {
  Settings,
  Plus,
  Trash2,
  CheckCircle2,
  DollarSign,
  CreditCard
};
